name: CI
on: [push, pull_request]
jobs:
  static-check:
    runs-on: ubuntu-latest 
    container:
      image: docker://registry.opensuse.org/home/syrianidou_sofia/containers/tumbleweed:o3-jobgroups
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get modified job group yaml files
        id: changed-files
        run: |
          git config --global --add safe.directory '*'
          CHANGED_FILES=$(git diff --diff-filter="*ACDMRTUX" --name-only origin/master job_groups/ | tr '\n' ' ')
          echo $CHANGED_FILES
          echo "::set-output name=files::${CHANGED_FILES}"

      - name: Run yamllint for modified job group schedules
        run: yamllint -f github job_groups.yaml ${{ steps.changed-files.outputs.files }}

      - name: Check for orphaned yaml files
        env:
          APIKEY: "${{ secrets.APIKEY }}"
          APISECRET: "${{ secrets.APISECRET }}"
        run: ./tool.py --orphans

      - name: Run serverside checks
        env:
          APIKEY: "${{ secrets.APIKEY }}"
          APISECRET: "${{ secrets.APISECRET }}"
        run: ./tool.py --dry-run --push

      - name: Clone os-autoinst-distri-opensuse repository
        uses: actions/checkout@v2
        with:
          repository: os-autoinst/os-autoinst-distri-opensuse 
          ref: refs/heads/master
          path: os-autoinst-distri-opensuse
          clean: false
          fetch-depth: 1
      - name: Check if YAML_SCHEDULE and YAML_TEST_DATA exist in os-autoinst-distri-opensuse
        run: |
          for file in ${{ steps.changed-files.outputs.files }}; do
            for file_ref in $(grep -oP '(YAML_SCHEDULE|YAML_TEST_DATA):\s\K.*' $file | tr -d "'" | tr -d '"' | sort -u | awk "{print \"os-autoinst-distri-opensuse/\" \$0}") ; do

              if ! test -f "$file_ref" ; then
                echo "Error: Reference from '${file}' to non existing '${file_ref}'"
                exit 1
              fi
            done
          done
