name: Deploy
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: docker://registry.opensuse.org/devel/openqa/ci/tw/containers/tumbleweed:o3-jobgroups
    steps:

      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Upload job group schedules to O3
        env:
          APIKEY: "${{ secrets.APIKEY }}"
          APISECRET: "${{ secrets.APISECRET }}"
        run: |
          ./tool.py --push --github
